import { StyleSheet } from "react-native";

const buttonStyles = StyleSheet.create({
  forgotPasswordButtonStyle: {
    marginTop: 25,
  },
  forgotPasswordButtontitleStyle: {
    color: "#ffaa97",
  },
  regularButton: {
    alignItems: "center",
    justifyContent: "center",
    width: "85%",
    height: "60",
    borderRadius: 60,
    borderWidth: 3,
  },
  logInButtonStyle: {
    marginTop: 25,
    borderColor: "#ffaa97",
    backgroundColor: "white",
  },
  registerButtonStyle: {
    marginTop: 13,
    borderColor: "white",
    backgroundColor: "#e8aca0",
  },
  logInTextButtonStyle: {
    color: "#ffaa97",
  },
  registerTextButtonStyle: {
    color: "white",
  },
  saveButtonStyle: {
    borderColor: "#436dff",
    backgroundColor: "#c9d5ff",
    alignSelf: "center",
    marginTop: 30,
  },
  saveTextButtonStyle: {
    color: "#436dff",
  },
  chatButtonsView: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    width: "90%",
    alignSelf: "center",
    marginTop: 5,
    borderRadius: 50,
    paddingVertical: 20,
  },
  chatButtonStyle: {
    width: 160,
    height: 60,
    borderRadius: 10,
    backgroundColor: "#e8aca0",
    alignItems: "center",
    justifyContent: "center",
  },
  photosAndVideosButtonStyle: {
    width: 175,
    height: 60,
    borderRadius: 10,
    backgroundColor: "#d1e7dd",
    alignSelf: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  chatButtonText: {
    color: "#fff3f1",
    fontWeight: "bold",
  },
  photosAndVideosButtonTextStyle: {
    color: "#fff3f1",
    color: "#6B7672",
    fontWeight: "bold",
    alignSelf: "center",
  },
  sendChatButtonStyle: {
    backgroundColor: "#ffe9e4",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
    width: 60,
  },
  sendChatTextButtonStyle: {
    color: "#e8aca0",
  },
  adminMenuButtonStyle: {
    width: 195,
    height: 80,
    borderRadius: 10,
    backgroundColor: "#d1e7dd",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  adminTextButtonStyle: {
    color: "#6B7672",
    fontWeight: "bold",
  },
  createCircularButtonStyle: {
    width: 175,
    height: 60,
    borderRadius: 10,
    backgroundColor: "#e8aca0",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginTop: 10,
  },
  createCircularTextButtonStyle: {
    color: "#fff3f1",
    fontWeight: "bold",
  },
  allCircularsButtonStyle: {
    width: "50%",
    height: 70,
    borderRadius: 10,
    backgroundColor: "#d1e7dd",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginTop: 40,
  },
  asignRoomToChildButton: {
    backgroundColor: "#e8aca0",
    borderRadius: 10,
    height: 30,
    width: 30,
    justifyContent: "center",
    alignContent: "center",
  },
  deleteTeacherButton: {
    backgroundColor: "#e74c3c",
    borderRadius: 10,
    height: 30,
    width: 30,
    justifyContent: "center",
    alignContent: "center",
  },
  chatRoomButton: {
    borderRadius: 10,
    backgroundColor: "#e8aca0",
    height: 30,
    width: 60,
    justifyContent: "center",
    alignItems: "center",
    margin: 10,
  },
  chatRoomButtonText: {
    color: "#fff3f1",
    fontWeight: "bold",
  },
  removeChildButton: {
    backgroundColor: "#e74c3c",
    borderRadius: 10,
    height: 30,
    width: 60,
    justifyContent: "center",
    alignItems: "center",
    margin: 10,
  },
  removeChildButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  removeAllButton: {
    backgroundColor: "#e74c3c",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 10,
  },
  removeAllButtonText: {
    color: "#fff",
    fontWeight: "bold",
  },
  roomsButtonView: {
    marginVertical: 10,
  },
  createRoomButtonView: {
    alignItems: "center",
    paddingTop: 20,
  },
  modalSelectorsView: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  multimediaButtonStyle: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
});

export default buttonStyles;
